services:
  api:
    image: ghcr.io/mosesmbadi/sms-emmy:latest
    container_name: sms-api
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - ENABLE_PROMETHEUS_METRICS=true
    restart: unless-stopped
    volumes:
      - ./messages.db:/app/messages.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
