# Prometheus Configuration for Production Monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sms-monitor'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # SMS Application metrics (remote targets)
  - job_name: 'sms-api'
    static_configs:
      # Will be replaced with actual application server IP during deployment
      - targets: ['<app-ip>:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Additional SMS API instances (for load balancing)
  - job_name: 'sms-api-secondary'
    static_configs:
      - targets: []  # Add secondary instances here
    metrics_path: '/metrics'
    scrape_interval: 30s

  # System metrics from monitoring server
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'

  # Alertmanager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
