# Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # SMS Application metrics (production deployment)
  - job_name: 'sms-api'
    static_configs:
      # Replace with actual application server IPs
      - targets: ['APPLICATION_SERVER_IP:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
